import type { ProductItem } from "@entities/productCard";
import { product5, product6, product4 } from "@shared/assets";
export const productsWithDiscount: ProductItem[] = [
  {
    id: "0",
    title: "Star Wars Outer Rim",
    image: product5,
    price: 32,
    players: "2-4",
    playingTime: "30-60",
    minAge: 18,
    discountPercent: 15,
  },
  {
    id: "1",
    title: "Red Dragon Tavern",
    image: product6,
    price: 32,
    players: "2-4",
    playingTime: "30-60",
    minAge: 18,
    discountPercent: 15,
  },
  {
    id: "2",
    title: "Gravity Falls: Save Waddles",
    image: product4,
    price: 32,
    players: "2-4",
    playingTime: "30-60",
    minAge: 18,
    discountPercent: 15,
  },
  {
    id: "3",
    title: "Star Wars Outer Rim",
    image: product5,
    price: 32,
    players: "2-4",
    playingTime: "30-60",
    minAge: 18,
    discountPercent: 15,
  },
  {
    id: "0",
    title: "Star Wars Outer Rim",
    image: product5,
    price: 32,
    players: "2-4",
    playingTime: "30-60",
    minAge: 18,
    discountPercent: 15,
  },
  {
    id: "1",
    title: "Red Dragon Tavern",
    image: product6,
    price: 32,
    players: "2-4",
    playingTime: "30-60",
    minAge: 18,
    discountPercent: 15,
  },
  {
    id: "2",
    title: "Gravity Falls: Save Waddles",
    image: product4,
    price: 32,
    players: "2-4",
    playingTime: "30-60",
    minAge: 18,
    discountPercent: 15,
  },
  {
    id: "3",
    title: "Star Wars Outer Rim",
    image: product5,
    price: 32,
    players: "2-4",
    playingTime: "30-60",
    minAge: 18,
    discountPercent: 15,
  },
];
