import type { ProductItem } from "@entities/product";
import { product1, product2, product3, product4 } from "@shared/assets";
export const products: ProductItem[] = [
  {
    id: "0",
    title: "Warhammer 40,000: Chaos Space Marines",
    image: product1,
    price: 32,
    players: "2-4",
    playingTime: "30-60",
    minAge: 18,
  },
  {
    id: "1",
    title: "To the mars",
    image: product2,
    price: 32,
    players: "2-4",
    playingTime: "30-60",
    minAge: 18,
  },
  {
    id: "2",
    title: "Broken Realms: Horrek's Dreadlance",
    image: product3,
    price: 32,
    players: "2-4",
    playingTime: "30-60",
    minAge: 18,
  },
  {
    id: "3",
    title: "Orks: Ghazghkull Thraka Collector's Edition",
    image: product4,
    price: 32,
    players: "2-4",
    playingTime: "30-60",
    minAge: 18,
  },
  {
    id: "0",
    title: "Warhammer 40,000: Chaos Space Marines",
    image: product1,
    price: 32,
    players: "2-4",
    playingTime: "30-60",
    minAge: 18,
  },
  {
    id: "1",
    title: "To the mars",
    image: product2,
    price: 32,
    players: "2-4",
    playingTime: "30-60",
    minAge: 18,
  },
  {
    id: "2",
    title: "Broken Realms: Horrek's Dreadlance",
    image: product3,
    price: 32,
    players: "2-4",
    playingTime: "30-60",
    minAge: 18,
  },
  {
    id: "3",
    title: "Orks: Ghazghkull Thraka Collector's Edition",
    image: product4,
    price: 32,
    players: "2-4",
    playingTime: "30-60",
    minAge: 18,
  },
];
